### ISSUE TITLE
Clone site error :sh: locale.x=en_FR: not found

### ISSUE THREAD

**Issue by kn0wledge** [sud0nick/PortalAuth#1]
Hi sud0nick,

when trying to clone a site, i get the below in the error log:
sh: locale.x=en_FR: not found

anyway around it?

**Comment by sud0nick** [comment]
I'm guessing that you are trying to clone a French site.  The Pineapple doesn't have the en_FR locale installed by default.  You'll want to see if you can get it installed and that should fix your issue.

**Comment by kn0wledge** [comment]
hmm the site is in English though... do you know anyway to install different locales on the pinapple?

**Comment by sud0nick** [comment]
I have not tried to install other locales on the Pineapple.  Try asking in the forums to see if anyone knows.
