### ISSUE TITLE
Dependencies not detected

### ISSUE THREAD

**Issue by CollegiateComputer** [sud0nick/PortalAuth#19]
When installing module manually from SSH via git, curl is not detected and module won't install dependencies via GUI on web interface. Attempted installing curl manually via SSH, but the module isn't detecting it and the GUI for the module on the pineapple management web interface complains that it needs to install dependencies.

**Comment by chinnidiwakar** [comment]
> 
> 
> When installing module manually from SSH via git, curl is not detected and module won't install dependencies via GUI on web interface. Attempted installing curl manually via SSH, but the module isn't detecting it and the GUI for the module on the pineapple management web interface complains that it needs to install dependencies.

i tried to install module from wifipineappe with version 1.7 which is having no dependecy issue(but tinycss issue),  and installed dependencies, and then replaced the portalauth with the version 1.8 from sud0nick github. as already dependencies are resolved page cloned successfully but it is not showing harverster box. cloning first time successful but later, it shows forbidden error.

**Comment by timelf123** [comment]
I have the same issue when cloning 1.8 from git, but was unable to resolve it by installing deps with 1.7 then swapping to 1.8

**Comment by CollegiateComputer** [comment]
I was able to make some slight progress by SSHing into the pineapple and giving the script that runs to check for and download dependencies executable permission (chmod +x ....). It looks like when installing from GitHub the executable files within the module don't automatically get executable permission. There are a lot of them that need it, so I'm in the process of writing a script to do it for me by file extension for the whole module.

**Comment by timelf123** [comment]
Thanks `chmod *.sh` worked

**Comment by CollegiateComputer** [comment]
I haven't had a chance to play around with it in a week, but just an FYI, in the 1.7 version that's available directly from hak5, there are a lot of other files besides .sh files with executable permission by default. Not sure if just giving shell scripts (.sh) executable permission is enough to prevent running into errors down the line, but it may be.

**Comment by sud0nick** [comment]
When you download the module from GitHub you need to chmod all of it.  Just SSH into the Pineapple, cd to /pineapple/modules/, and run `chmod 755 -R PortalAuth/`.  Sorry for not getting the latest version to the module manager but school and work are eating up all of my time at the moment.
