### ISSUE TITLE
If you have problem with tinycss - do this :)

### ISSUE THREAD

**Issue by 0k00l** [sud0nick/PortalAuth#24]
Complete trace(from errorl log): 
**Traceback (most recent call last): File "/pineapple/modules/PortalAuth/includes/scripts/portalclone.py", line 4, in from PortalCloner import PortalCloner File "/sd/modules/PortalAuth/includes/scripts/PortalCloner.py", line 18, in import tinycss ImportError: No module named tinycss**

Do:
* cd /sd/modules/PortalAuth/includes/scripts/libs/tinycss
* ```sh touch __init__.py ```
*  cd ../..
* vim PortalCloner.py
and change line:
```python
import tinycss
```
to
```python
from tinycss import tinycss
```

**Comment by sud0nick** [comment]
Or just download the latest version of the module where this isn't an issue...
