### ISSUE TITLE
Nano is having issue with tinycss

### ISSUE THREAD

**Issue by wpa-2** [sud0nick/PortalAuth#25]
I installed module via app manager and getting this error. 
`Traceback (most recent call last): File "/pineapple/modules/PortalAuth/includes/scripts/portalclone.py", line 4, in from PortalCloner import PortalCloner File "/sd/modules/PortalAuth/includes/scripts/PortalCloner.py", line 18, in import tinycss ImportError: No module named tinycss`

**Comment by sud0nick** [comment]
You need to install the module from GitHub.  The Module Manager one hasn't been updated in forever because my PR's haven't been reviewed for some reason.

**Comment by wpa-2** [comment]
Is there any install instruction's to do this ?

**Comment by sud0nick** [comment]
Clone the repo and move the directory into the /pineapple/modules/ directory on the Pineapple.  Then run `chmod -R 755 /pineapple/modules/PortalAuth/`.
