### ISSUE TITLE
AttributeError: 'module' object has no attribute 'make_parser'

### ISSUE THREAD

**Issue by tkal** [sud0nick/PortalAuth#26]
When I'm trying to make a clone of a site I get the following error.

```
Traceback (most recent call last):
  File "/pineapple/modules/PortalAuth/includes/scripts/portalclone.py", line 25, in <module>
    cloner.cloneResources()
  File "/sd/modules/PortalAuth/includes/scripts/PortalCloner.py", line 199, in cloneResources
    self.css_urls[_key] = self.parseCSS(urlparse.urljoin(self.url, img.get(tag)))
  File "/sd/modules/PortalAuth/includes/scripts/PortalCloner.py", line 67, in parseCSS
    parser = tinycss.make_parser('page3')
AttributeError: 'module' object has no attribute 'make_parser'
```

I have't been able to fix the issue with the sources available online.

**Comment by sud0nick** [comment]
hmm that's a new one.  What version of the module are you using?  And can you tell me which version of tinycss exists in `/sd/modules/PortalAuth/includes/scripts/libs/tinycss/version.py`?

**Comment by tkal** [comment]
Module version is 1.9 (which is the latest) and for tiny css version=0.4.

**Comment by sud0nick** [comment]
I know this issue is old and you may not even be using the module anymore but I figured I'd mention I'm no longer maintaining it as there are too many limitations currently on the Pineapple that make modernizing this module near impossible.
